### ISSUE TITLE
Stuck at "Typescript project is initializing".

### ISSUE THREAD

**Issue by belohlavek** [Phaiax/ArcticTypescript#26]
Error:
```
Typescript initializing MY_FILESYSTEM\T3STest\main.ts
Exception in thread Thread-3:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "MY_FILESYSTEM\AppData\Roaming\Sublime Text 3\Packages\ArcticTypescript\lib\system\Processes.py", line 162, in run
    self.tss_process = Popen([node, tss, self.root], stdin=PIPE, stdout=PIPE, stderr=PIPE, **kwargs)
TypeError: type object got multiple values for keyword argument 'stderr'

Exception in thread Thread-4:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "MY_FILESYSTEM\AppData\Roaming\Sublime Text 3\Packages\ArcticTypescript\lib\system\Processes.py", line 162, in run
    self.tss_process = Popen([node, tss, self.root], stdin=PIPE, stdout=PIPE, stderr=PIPE, **kwargs)
TypeError: type object got multiple values for keyword argument 'stderr' 
```

**Comment by Phaiax** [comment]
i released a new version a 1-2 hours ago, but it seems like this error also would occur with the old version you are using. (I changed exactly that line  :D)

Wait until https://packagecontrol.io/packages/ArcticTypescript shows the most recent version 0.5.1, then restart sublime to trigger an update via package manager.
