### ISSUE TITLE
Random error started appearing

### ISSUE THREAD

**Issue by pocesar** [Phaiax/ArcticTypescript#49]
haven't changed anything, went to sleep, and the other day it wasn't working anymore
```
ArcticTypescript: error   : typescript-tools error: 
 G:\Dropbox\ST3\Data\Packages\ArcticTypescript\bin\tss.js:190

            seenNoDefaultLib = seenNoDefaultLib || source.hasNoDefaultLib;
                                                         ^

TypeError: Cannot read property 'hasNoDefaultLib' of undefined
    at G:\Dropbox\ST3\Data\Packages\ArcticTypescript\bin\tss.js:190:58
    at Array.forEach (native)
    at TSS.setup (G:\Dropbox\ST3\Data\Packages\ArcticTypescript\bin\tss.js:188:24)
    at Object.<anonymous> (G:\Dropbox\ST3\Data\Packages\ArcticTypescript\bin\tss.js:600:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
```

**Comment by Phaiax** [comment]
is fixed (Release will follow in a few hours).
